# Generated by Django 2.2.3 on 2019-09-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('std_num', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='학번')),
                ('login_id', models.CharField(max_length=13, null=True, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='이름')),
                ('team_name', models.CharField(max_length=16, null=True, verbose_name='소속팀')),
                ('position', models.SmallIntegerField(null=True, verbose_name='직책')),
                ('major', models.CharField(max_length=64, null=True, verbose_name='학과')),
                ('grade', models.SmallIntegerField(null=True, verbose_name='학년')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='학적상태')),
                ('phone_num', models.CharField(max_length=11, null=True, verbose_name='전화번호')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='수정일')),
                ('is_sign_up', models.BooleanField(default=False, verbose_name='회원가입여부')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('std_num_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
