# Generated by Django 2.2.3 on 2019-09-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('type_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('board_type', models.CharField(max_length=32, verbose_name='게시판종류')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('file', models.FileField(upload_to='', verbose_name='파일')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('file_no', models.CharField(max_length=1024, verbose_name='파일')),
                ('notify', models.BooleanField(default=False, null=True, verbose_name='공지여부')),
                ('category', models.CharField(max_length=32, null=True, verbose_name='카테고리')),
                ('ip_address', models.CharField(max_length=14, null=True, verbose_name='아이피')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='수정일')),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BoardType')),
                ('std_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
        ),
    ]
